using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using Pos.Data;
using System.Data.Entity;

namespace Pos.UI
{
    public partial class OrderForm : XtraForm
    {
        public OrderForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Pos.Data.PosEntities dbContext = new Pos.Data.PosEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.SalesLines.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    salesLinesBindingSource.DataSource = dbContext.SalesLines.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        protected override void OnLoad(EventArgs e)
        {
            base.OnLoad(e);
            GrcSales.DataSource = salesLines;
        }

        List<SalesLine> salesLines = new List<SalesLine>();
            

        private void MenuButtonClicked(object sender, EventArgs e)
        {
            var menu = DataRepository.Menu.GetByName(((SimpleButton)sender).Text.ToString());
            var salesLine = new SalesLine();
            // 새로 들어갈 라인
            salesLine.MenuName = menu.Name;
            salesLine.MenuUnitPrice = menu.UnitPrice;
            
            

            // 중복된 이름이 없을경우
            var existingSalesLine = salesLines.FirstOrDefault(x => x.MenuName == salesLine.MenuName);

            if (existingSalesLine == null)
            {
                salesLine.Quantity++;
                salesLine.TotalPrice = salesLine.MenuUnitPrice;
                salesLines.Add(salesLine);
            }
            else
            {
                existingSalesLine.Quantity++;
                existingSalesLine.TotalPrice = existingSalesLine.MenuUnitPrice * existingSalesLine.Quantity;
                // 있음
                // quantity ++
            }

            GrvSales.RefreshData();
        }
    }
}