using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using System.Data.Entity;

namespace Pos.UI
{
    public partial class SalesCancelForm : DevExpress.XtraEditors.XtraForm
    {
        public SalesCancelForm()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Pos.Data.PosEntities dbContext = new Pos.Data.PosEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Sales.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
    salesBindingSource.DataSource = dbContext.Sales.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}